# 2.2 数据操作

## 2.2.1 创建 Tensor


In [7]:
# 引入 Pytorch
import torch

# 创建一个初始化 Tensor
x = torch.empty(5, 3)

print(x)

tensor([[0.0000e+00, 1.5846e+29, 6.4852e-21],
        [2.8615e-42, 1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [9]:
# 随机初始化
x = torch.rand(5, 3)
print(x)

tensor([[0.7277, 0.6169, 0.4449],
        [0.3564, 0.4589, 0.4274],
        [0.6536, 0.8069, 0.6462],
        [0.5669, 0.2318, 0.0715],
        [0.1958, 0.0025, 0.8759]])


In [12]:
# 全是 0 的 Tensor
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# 打印 shape
print(x.size())

torch.Size([5, 3])


## 2.2.1 操作

In [14]:
# 加法
y = torch.rand(5, 3)

print(x + y)

tensor([[0.3880, 0.5582, 0.1560],
        [0.2924, 0.4125, 0.2106],
        [0.5914, 0.1143, 0.0205],
        [0.0369, 0.9089, 0.4131],
        [0.1110, 0.0160, 0.1169]])


In [17]:
# 索引
y[0, :-1]

tensor([0.3880, 0.5582])

In [18]:
# 改变形状
y = x.view(15)

In [19]:
y

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])