# 2.3 自动求梯度

## 2.3.1 概念

`requires_grad` 设置为 `True`，自动追踪在其上所有操作，可以调用 `.backward()` 来完成所有梯度计算。

## 2.3.2 Tensor

In [2]:
import torch

In [5]:
# 创建 tensor 并设置 require_grad=True
x = torch.ones(5, 1, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]], requires_grad=True)
None


In [6]:
y = x + 2

In [7]:
print(y.grad_fn)

In [8]:
z = y * y * 2
out = z.mean()

In [9]:
print(z)

tensor([[18.],
        [18.],
        [18.],
        [18.],
        [18.]], grad_fn=<MulBackward0>)


In [10]:
print(out)

tensor(18., grad_fn=<MeanBackward0>)


In [11]:
out.backward()

In [12]:
x.grad

tensor([[2.4000],
        [2.4000],
        [2.4000],
        [2.4000],
        [2.4000]])